name: rl-project
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - flax==0.7.4
      - gym==0.25.2
      - huggingface-hub==0.17.3
      - textworld==1.5.4
      - transformers==4.34.1
      - autoawq
      # PyTorch must be installed using pip on WSL otherwise it won't detect your GPU. Amazing.
      - torch
      - torchvision
      - torchaudio
      - trl
